version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: b2b_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    working_dir: /app
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5174:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

volumes:
  pgdata: